#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$PG_USER" --dbname "$PG_DATABASE" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
    CREATE USER $DB_USERNAME WITH PASSWORD '$DB_PASSWORD';
    CREATE SCHEMA $PG_DATABASE;
    GRANT ALL PRIVILEGES ON SCHEMA $PG_DATABASE TO $DB_USERNAME;
EOSQL
