--- User Setup
CREATE USER "${PG_USER}" LOGIN;
ALTER USER "${PG_USER}" PASSWORD '${PG_PASSWORD}';

CREATE DATABASE ${PG_DATABASE};
GRANT ALL PRIVILEGES ON DATABASE ${PG_DATABASE} TO "${PG_USER}";

--- PG_DATABASE Setup

\c ${PG_DATABASE}

CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
CREATE EXTENSION IF NOT EXISTS pgaudit;
