#!/bin/bash
docker pull aaidocker/aai-hbase-1.2.3:latest
docker pull attos/dmaap:latest
docker pull dorowu/ubuntu-desktop-lxde-vnc
docker pull mariadb:10
docker pull mysql/mysql-server:5.6
docker pull nexus3.onap.org:10001/mariadb:10.1.11
docker pull nexus3.onap.org:10001/openecomp/admportal-sdnc-image:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/ajsc-aai:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/appc-image:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/dgbuilder-sdnc-image:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/model-loader:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/mso:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/policy/policy-db:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/policy/policy-drools:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/policy/policy-nexus:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/policy/policy-pe:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/portalapps:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/portaldb:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/sdc-backend:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/sdc-cassandra:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/sdc-elasticsearch:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/sdc-frontend:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/sdc-kibana:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/sdnc-image:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/testsuite:1.0-STAGING-latest
docker pull nexus3.onap.org:10001/openecomp/vid:1.0-STAGING-latest
docker pull oomk8s/config-init:1.0.0
docker pull oomk8s/mariadb-client-init:1.0.0
docker pull oomk8s/readiness-check:1.0.0
docker pull oomk8s/ubuntu-init:1.0.0
docker pull wurstmeister/kafka:latest
docker pull wurstmeister/zookeeper:latest
docker pull ubuntu:16.04
