{{- /* AAI EVENT TOPIC */ -}}
{{- if .Values.aai.notifications.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .Values.aai.notifications.topic.name | lower }}-kafka-topic
  labels:
    {{- include "common.labels" . | nindent 4 }}
    strimzi.io/cluster: {{ include "common.namespace" . }}-strimzi
    helm.sh/resource-policy: keep
spec:
  topicName: {{ .Values.aai.notifications.topic.name }}
---
{{- end }}

{{- /* DELTA EVENT TOPIC */ -}}
{{- if .Values.delta.events.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .Values.delta.events.topic.name | lower }}-kafka-topic
  labels:
    {{- include "common.labels" . | nindent 4 }}
    strimzi.io/cluster: {{ include "common.namespace" . }}-strimzi
    helm.sh/resource-policy: keep
spec:
  topicName: {{ .Values.delta.events.topic.name }}
{{- end }}
