# MSO updates to the default camunda schema.
USE `camundabpmn`;
ALTER TABLE ACT_HI_VARINST MODIFY TEXT_ LONGTEXT;

ALTER TABLE ACT_HI_DETAIL MODIFY TEXT_ LONGTEXT;

ALTER TABLE ACT_RU_VARIABLE MODIFY TEXT_ LONGTEXT;

INSERT INTO ACT_GE_PROPERTY VALUES ('historyLevel','3',1) ON DUPLICATE KEY UPDATE VALUE_='3';

CREATE TABLE IF NOT EXISTS ATT_URN_MAPPING AS SELECT * FROM ACT_GE_PROPERTY WHERE NAME_='-';
