#!/bin/bash

NENG_DB_PASS=$(echo $NENG_PASS)
NENG_DB_USER=$(echo $NENG_USER)
ROOT_PWD=$(echo $MYSQL_ROOT_PWD)
MARIADB_GALERA_HOST=$(echo $MARIADB_HOST)
NENG_DB_NAME=$(echo $NENG_DB)
NENG_DB_HOST=$(echo $NENG_HOST)

mysql -h$MARIADB_GALERA_HOST -uroot -p$ROOT_PWD -e \
  "DROP USER '${NENG_DB_USER}'@'%'"
mysql -h$MARIADB_GALERA_HOST -uroot -p$ROOT_PWD -e \
  "CREATE OR REPLACE USER '${NENG_DB_USER}'@'%' IDENTIFIED BY '${NENG_DB_PASS}'"
mysql -h$MARIADB_GALERA_HOST -uroot -p$ROOT_PWD -e \
  "GRANT ALL PRIVILEGES ON *.* TO '${NENG_DB_USER}'@'%'"
mysql -h$MARIADB_GALERA_HOST -uroot -p$ROOT_PWD $NENG_DB_NAME \
  < /my-data/nengdb-backup.sql
